C#/01/MVC/MVCTest/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTest.Controllers
{
    public class AjaxController : Controller
    {
        //
        // GET: /Ajax/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetDate()
        {
            System.Threading.Thread.Sleep(1000);
            return Content(System.DateTime.Now.ToString());
        }
    }
}

C#/01/MVC/MVCTest/Views/Ajax/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.8.2.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        $(function ()
        {
            $("#btnJQAjax").click(function ()
            {
                $.ajax(
                    {
                        url: "/Ajax/GetDate",
                        type: "post",
                        data: {},
                        success: function (date)
                        {
                            alert(date);
                        }
                    });
            });

        });
        function afterSuccess(data)
        {
            alert(data);
        }
        $(function () {
            $("#btnTest").click(function ()
            {
                alert("点击啊");
            });
        });
    </script>
</head>
<body>
    <div>
        <input type="button" value="获取时间(jquery异步)" id="btnJQAjax" />
    </div>
    <hr />
    @using (Ajax.BeginForm("GetDate", "Ajax", new AjaxOptions()
        {
            Confirm = "确认提交啊",
            HttpMethod = "Post",
            UpdateTargetId = "resutDiv",
            InsertionMode=InsertionMode.Replace,
            OnSuccess = "afterSuccess",
            LoadingElementId = "loadingDiv"
        }))
    { 
        <input type="text" />
        <input type="submit" value="获取时间(MVC异步)" />
     
    }
    <div  id="resutDiv"> </div>
    <hr />
        <div id="loadingDiv" >
            <img src="~/Content/loading.gif" height="40" width="40"  />
        </div>
    <hr />
    <input type="button"  value="按钮"  id="btnTest"/>
</body>
</html>